### ISSUE TITLE
Issue on page /L2/Lab2.html

### ISSUE THREAD

**Issue by thec0dewriter** [UBB-DB/AB2_MiniABKR#3]
Your issue content here.

**Comment by levilevente** [comment]
Szia @thec0dewriter! Adódott egy kérdésem a miniABKR-el kapcsolatosan. Amikor a MongoDB-t használjuk, akkor csak egy adatbázisunk lehet, vagy minden adatbázisunknak megfelel egy MongoDB adatbázis?
![image](https://github.com/UBB-DB/AB2_MiniABKR/assets/155687665/951befd0-cbea-460d-a538-eb6e3fad6ed9)
vagy
![image2](https://github.com/UBB-DB/AB2_MiniABKR/assets/155687665/bce50d7e-f9c7-485e-b6ae-330f302c4542)

**Comment by thec0dewriter** [comment]
Szia @levilevente 
Koszi hogy szóltál itt is. Hozzaadtam erre vonatkozolag is egy sort.
