### ISSUE TITLE
Issue on page /L2/Lab2.html

### ISSUE THREAD

**Issue by ZoltaniSzabolcs** [UBB-DB/AB2_MiniABKR#6]
Az adatbázis tábláinak attribútumait is tegyük bele a fa nézetbe?
> Implementaljatok egy [TreeView](https://en.wikipedia.org/wiki/Tree_view)-t az adatbazis objektumok megjelenitesere

![image](https://github.com/UBB-DB/AB2_MiniABKR/assets/152523188/0c2331c4-6e39-4a49-ba45-087dfecbf4fa)
(itt a tábláknak az attribútumait nem listázom)

**Comment by thec0dewriter** [comment]
Köszi @ZoltaniSzabolcs  a viszajelzest, kiegeszitettem a szoveget, nektek a jelen formaban is elegando(adatbazis/tabla) de majd a jovoben jo lenne ha hozzaadjuk az egyeb elemeket is valamint a CLI verzio is kilistazza a tobbi informaciot.
